version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports: ["2181:2181"]

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports: ["9092:9092"]
    depends_on:
      - zookeeper

  postgres-audit:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: molam_audit
      POSTGRES_USER: molam
      POSTGRES_PASSWORD: molam_pass
    ports: ["5433:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../sql:/docker-entrypoint-initdb.d

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports: ["9000:9000","9001:9001"]
    volumes:
      - miniodata:/data

  opensearch:
    image: opensearchproject/opensearch:2.9.0
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      "OPENSEARCH_JAVA_OPTS": "-Xms512m -Xmx512m"
      plugins.security.disabled: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports: ["9200:9200","9600:9600"]

  audit-writer:
    build: ../services/audit-writer
    environment:
      POSTGRES_DSN: postgres://molam:molam_pass@postgres-audit:5432/molam_audit
      KAFKA_BROKERS: kafka:9092
      AUDIT_TOPIC: molam.audit.events
      KMS_KEY_ID: local
      USE_AWS_KMS: "false"
    depends_on: [ kafka, postgres-audit ]
    restart: unless-stopped

  batch-uploader:
    build: ../services/batch-uploader
    environment:
      POSTGRES_DSN: postgres://molam:molam_pass@postgres-audit:5432/molam_audit
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: molam-audit
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      KMS_KEY_ID: local
      UPLOAD_INTERVAL_MS: "15000"
    depends_on: [ postgres-audit, minio ]
    restart: unless-stopped

  indexer:
    build: ../services/indexer
    environment:
      POSTGRES_DSN: postgres://molam:molam_pass@postgres-audit:5432/molam_audit
      OPENSEARCH_NODE: http://opensearch:9200
      INDEX_INTERVAL_MS: "30000"
    depends_on: [ postgres-audit, opensearch ]
    restart: unless-stopped

  verifier:
    build: ../services/verifier
    environment:
      POSTGRES_DSN: postgres://molam:molam_pass@postgres-audit:5432/molam_audit
      PORT: "4100"
    ports: ["4100:4100"]
    depends_on: [ postgres-audit ]
    restart: unless-stopped

volumes:
  pgdata:
  miniodata:
