apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-update-profile
  namespace: molam-id
  labels:
    app: id-update-profile
    component: profile
spec:
  replicas: 3
  selector:
    matchLabels:
      app: id-update-profile
  template:
    metadata:
      labels:
        app: id-update-profile
    spec:
      containers:
      - name: id-update-profile
        image: molam/id-update-profile:latest
        ports:
        - containerPort: 3018
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3018"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: connection-string
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: url
        - name: JWT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-keys
              key: public-key
        - name: KAFKA_ENABLED
          value: "true"
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: broker
        - name: WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: webhook-secret
              key: secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /livez
            port: 3018
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3018
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: id-update-profile
  namespace: molam-id
spec:
  type: ClusterIP
  ports:
  - port: 3018
    targetPort: 3018
  selector:
    app: id-update-profile
