openapi: 3.0.3
info:
  title: Molam ID - Session Monitoring
  version: "1.0.0"
  description: Real-time session monitoring and management for Molam ID
paths:
  /api/id/sessions/me:
    get:
      summary: List my active sessions (user self-service)
      tags:
        - Sessions
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessions:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        channel:
                          type: string
                          enum: [mobile, web, ussd, api]
                        device_id:
                          type: string
                        ip:
                          type: string
                        user_agent:
                          type: string
                        geo_country:
                          type: string
                        created_at:
                          type: string
                          format: date-time
                        last_seen_at:
                          type: string
                          format: date-time
                        expires_at:
                          type: string
                          format: date-time
                        is_active:
                          type: boolean

  /api/id/sessions/{sessionId}/revoke:
    post:
      summary: Revoke one of my sessions (or by admin)
      tags:
        - Sessions
      security:
        - bearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Revoked
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
        "404":
          description: Session not found or already inactive

  /api/id/sessions/revoke_all:
    post:
      summary: Revoke all my sessions except current
      tags:
        - Sessions
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Revoked
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  count:
                    type: integer

  /api/id/sessions/heartbeat:
    post:
      summary: Heartbeat to extend rolling expiration and last_seen_at
      tags:
        - Sessions
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  format: uuid
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
        "404":
          description: Session not found or inactive

  /api/id/admin/sessions/user/{userId}:
    get:
      summary: Admin list sessions for a user (ID domain only)
      tags:
        - Admin Sessions
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Session'

  /api/id/admin/sessions/revoke:
    post:
      summary: Admin revoke sessions by filter (channel/device/older-than)
      tags:
        - Admin Sessions
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  format: uuid
                channel:
                  type: string
                  enum: [mobile, web, ussd, api]
                deviceId:
                  type: string
                olderThanMinutes:
                  type: integer
      responses:
        "200":
          description: Revoked
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  count:
                    type: integer

  /api/id/admin/sessions/policies:
    get:
      summary: Read session/anomaly policies
      tags:
        - Admin Policies
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
    put:
      summary: Update session/anomaly policies (4-eyes via Brique 33 if sensitive)
      tags:
        - Admin Policies
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        "200":
          description: Updated

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Session:
      type: object
      properties:
        id:
          type: string
          format: uuid
        channel:
          type: string
          enum: [mobile, web, ussd, api]
        device_id:
          type: string
        ip:
          type: string
        geo_country:
          type: string
        created_at:
          type: string
          format: date-time
        last_seen_at:
          type: string
          format: date-time
        expires_at:
          type: string
          format: date-time
        is_active:
          type: boolean