apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-export-profile
  namespace: molam-id
  labels:
    app: id-export-profile
    component: export
spec:
  replicas: 2
  selector:
    matchLabels:
      app: id-export-profile
  template:
    metadata:
      labels:
        app: id-export-profile
    spec:
      containers:
      - name: id-export-profile
        image: molam/id-export-profile:latest
        ports:
        - containerPort: 3019
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3019"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: connection-string
        - name: JWT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-keys
              key: public-key
        - name: S3_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: s3-config
              key: endpoint
        - name: S3_REGION
          valueFrom:
            configMapKeyRef:
              name: s3-config
              key: region
        - name: S3_BUCKET
          value: "molam-exports"
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: access-key-id
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secret-access-key
        - name: S3_FORCE_PATH_STYLE
          value: "false"
        - name: KAFKA_ENABLED
          value: "true"
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: broker
        - name: WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: webhook-secret
              key: secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /livez
            port: 3019
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3019
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: id-export-profile
  namespace: molam-id
spec:
  type: ClusterIP
  ports:
  - port: 3019
    targetPort: 3019
  selector:
    app: id-export-profile
